spring:
  application:
    name: invitation
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 300000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 150000
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

telegram:
  notify_user_id: 237303826
